services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./bin/dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    environment:
      DATABASE_URL: postgres://rails:password@db:5432/rails_development
    depends_on:
      - db

volumes:
  bundle_data:
  postgres_data: