# 1. ベースイメージ
FROM ruby:3.4.3

# 2. 必要パッケージ
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libsqlite3-dev \
    libpq-dev \
    curl \
    libvips \
    nodejs \
    npm && \
    npm install -g corepack && \
    rm -rf /var/lib/apt/lists/*

# 3. 作業ディレクトリ
WORKDIR /app

# 4. Bundler設定
ENV BUNDLE_PATH=/usr/local/bundle

# 5. Gemインストール
COPY Gemfile Gemfile.lock ./
RUN bundle install

# 6. アプリコピー
COPY . .

# 7. 実行権限
RUN chmod +x bin/dev

# 8. entrypoint
COPY <<-"EOF" /usr/bin/entrypoint.sh
#!/bin/bash
set -e
rm -f /app/tmp/pids/server.pid
exec "$@"
EOF

RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

# 9. ポート
EXPOSE 3000

# 10. 起動
CMD ["./bin/dev"]